# Generated by Django 3.0.5 on 2020-05-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Charakter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=50)),
                ('klasse', models.CharField(choices=[('BARBARIAN', 'Barbarian'), ('BARD', 'Bard'), ('CLERIC', 'Cleric'), ('DRUID', 'Druid'), ('FIGHTER', 'Fighter'), ('MONK', 'Monk'), ('PALADIN', 'Paladin'), ('RANGER', 'Ranger'), ('ROGUE', 'Rogue'), ('SORCERER', 'Sorcerer'), ('WARLOCK', 'Warlock'), ('WIZARD', 'Wizard')], max_length=10)),
                ('niveau', models.PositiveSmallIntegerField(default=1)),
                ('rasse', models.CharField(choices=[('DWARF', 'Dwarf'), ('HALFLING', 'Halfling'), ('HUMAN', 'Human'), ('DRAGONBORN', 'Dragonborn'), ('GNOME', 'Gnome'), ('HALF-ELF', 'Half-Elf'), ('HALF-ORC', 'Half-Orc'), ('TIEFLING', 'Tiefling'), ('GOLIATH', 'Goliath')], max_length=12)),
                ('herkunft', models.CharField(max_length=25)),
                ('ausrichtung', models.CharField(choices=[('LG', 'Lawful Good'), ('LN', 'Lawful Neutral'), ('LE', 'Lawful Evil'), ('NG', 'Neutral Good'), ('TN', 'True Neutral'), ('NE', 'Neutral Evil'), ('CG', 'Chaotic Good'), ('CN', 'Chaotic Neutral'), ('CE', 'Chaotic Evil')], max_length=2)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.Player')),
            ],
        ),
    ]
