# Generated by Django 3.0.5 on 2020-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charakter',
            name='rasse',
            field=models.CharField(choices=[('DWARF', 'Dwarf'), ('ELF', 'Elf'), ('HALFLING', 'Halfling'), ('HUMAN', 'Human'), ('DRAGONBORN', 'Dragonborn'), ('GNOME', 'Gnome'), ('HALF-ELF', 'Half-Elf'), ('HALF-ORC', 'Half-Orc'), ('TIEFLING', 'Tiefling'), ('GOLIATH', 'Goliath')], max_length=12),
        ),
    ]
